services:
  mongo:
    image: mongo:latest
    container_name: mern_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db
    networks:
      - mern_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mern_backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app  # Mount backend files to allow live reloading
      - /app/node_modules  # Prevent overwriting node_modules
    depends_on:
      - mongo
    networks:
      - mern_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mern_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - mern_network

volumes:
  mongo_data:

networks:
  mern_network:
    driver: bridge
