services:
  mongo:
    image: mongo:latest
    container_name: mern_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo_data:/data/db
    networks:
      - mern_network
  
  backend-flask:
    container_name: ai-backend
    restart: always
    ports:
      - "5050:5050"
    build:
      context: ./backend_fer
      dockerfile: Dockerfile
    volumes:
      - ./backend_fer:/app
    networks:
      - mern_network

  nlp:
    build:
      context: ./nlp
      dockerfile: Dockerfile
    container_name: nlp_topic_modeling
    environment:
      - API_KEY=your_secret_api_key_here
    ports:
      - "5010:5010"
    volumes:
      - ./nlp:/app
    depends_on:
      - backend
    networks:
      - mern_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mern_backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app  # Mount backend files to allow live reloading
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017/hackaton-mia-2025?authSource=admin
    depends_on:
      - mongo
    networks:
      - mern_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mern_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - backend-flask
    networks:
      - mern_network

volumes:
  mongo_data:

networks:
  mern_network:
    driver: bridge
